pages = [{"l":"index.html#","e":false,"i":"","n":"root","t":"root","d":"","k":"static","x":""},
{"l":"com/alecdorrington.html#","e":false,"i":"","n":"com.alecdorrington","t":"com.alecdorrington","d":"","k":"package","x":""},
{"l":"com/alecdorrington/client.html#","e":false,"i":"","n":"com.alecdorrington.client","t":"com.alecdorrington.client","d":"","k":"package","x":""},
{"l":"com/alecdorrington/client/dev.html#","e":false,"i":"","n":"com.alecdorrington.client.dev","t":"com.alecdorrington.client.dev","d":"","k":"package","x":""},
{"l":"com/alecdorrington/client/dev/HotReload$.html#","e":false,"i":"","n":"HotReload","t":"HotReload","d":"com.alecdorrington.client.dev","k":"object","x":""},
{"l":"com/alecdorrington/client/dev/HotReload$.html#enable-94c","e":false,"i":"","n":"enable","t":"enable(): Unit","d":"com.alecdorrington.client.dev.HotReload","k":"def","x":""},
{"l":"com/alecdorrington/client/views.html#","e":false,"i":"","n":"com.alecdorrington.client.views","t":"com.alecdorrington.client.views","d":"","k":"package","x":""},
{"l":"com/alecdorrington/client/views/IndexView$.html#","e":false,"i":"","n":"IndexView","t":"IndexView extends View","d":"com.alecdorrington.client.views","k":"object","x":""},
{"l":"com/alecdorrington/client/views/View.html#","e":false,"i":"","n":"View","t":"View","d":"com.alecdorrington.client.views","k":"class","x":""},
{"l":"com/alecdorrington/client/views/View.html#content-0","e":false,"i":"","n":"content","t":"content: Base","d":"com.alecdorrington.client.views.View","k":"def","x":""},
{"l":"com/alecdorrington/client/views/View.html#show-571","e":false,"i":"","n":"show","t":"show(rootName: String = ...): Unit","d":"com.alecdorrington.client.views.View","k":"def","x":""},
{"l":"com/alecdorrington/common.html#","e":false,"i":"","n":"com.alecdorrington.common","t":"com.alecdorrington.common","d":"","k":"package","x":""},
{"l":"com/alecdorrington/common/Stub.html#","e":false,"i":"","n":"Stub","t":"Stub","d":"com.alecdorrington.common","k":"class","x":""},
{"l":"com/alecdorrington/server.html#","e":false,"i":"","n":"com.alecdorrington.server","t":"com.alecdorrington.server","d":"","k":"package","x":""},
{"l":"com/alecdorrington/server/api.html#","e":false,"i":"","n":"com.alecdorrington.server.api","t":"com.alecdorrington.server.api","d":"","k":"package","x":""},
{"l":"com/alecdorrington/server/api/CoreApi$.html#","e":false,"i":"","n":"CoreApi","t":"CoreApi","d":"com.alecdorrington.server.api","k":"object","x":""},
{"l":"com/alecdorrington/server/api/CoreApi$.html#assets-0","e":false,"i":"","n":"assets","t":"assets: PublicEndpoint[(List[String], Option[String]), StatusCode, (Array[Byte], String, String, String), Any]","d":"com.alecdorrington.server.api.CoreApi","k":"val","x":""},
{"l":"com/alecdorrington/server/api/CoreApi$.html#health-0","e":false,"i":"","n":"health","t":"health: Endpoint[Unit, Unit, Unit, String, Any]","d":"com.alecdorrington.server.api.CoreApi","k":"val","x":""},
{"l":"com/alecdorrington/server/api/CoreApi$.html#hotReload-0","e":false,"i":"","n":"hotReload","t":"hotReload: Endpoint[Unit, Unit, Unit, Stream[IO, String] => Stream[IO, String], Fs2Streams[IO] & WebSockets]","d":"com.alecdorrington.server.api.CoreApi","k":"val","x":""},
{"l":"com/alecdorrington/server/api/CoreApi$.html#index-0","e":false,"i":"","n":"index","t":"index: Endpoint[Unit, Unit, Unit, String, Any]","d":"com.alecdorrington.server.api.CoreApi","k":"val","x":""},
{"l":"com/alecdorrington/server/config.html#","e":false,"i":"","n":"com.alecdorrington.server.config","t":"com.alecdorrington.server.config","d":"","k":"package","x":""},
{"l":"com/alecdorrington/server/config/Env$.html#","e":false,"i":"","n":"Env","t":"Env","d":"com.alecdorrington.server.config","k":"object","x":""},
{"l":"com/alecdorrington/server/config/Env$.html#ASSETS_DIR-0","e":false,"i":"","n":"ASSETS_DIR","t":"ASSETS_DIR: Path","d":"com.alecdorrington.server.config.Env","k":"val","x":""},
{"l":"com/alecdorrington/server/config/Env$.html#DEV_MODE-0","e":false,"i":"","n":"DEV_MODE","t":"DEV_MODE: Boolean","d":"com.alecdorrington.server.config.Env","k":"val","x":""},
{"l":"com/alecdorrington/server/config/Env$.html#HOST-0","e":false,"i":"","n":"HOST","t":"HOST: String","d":"com.alecdorrington.server.config.Env","k":"val","x":""},
{"l":"com/alecdorrington/server/config/Env$.html#NAME-0","e":false,"i":"","n":"NAME","t":"NAME: String","d":"com.alecdorrington.server.config.Env","k":"val","x":""},
{"l":"com/alecdorrington/server/config/Env$.html#PORT-0","e":false,"i":"","n":"PORT","t":"PORT: Int","d":"com.alecdorrington.server.config.Env","k":"val","x":""},
{"l":"com/alecdorrington/server/config/Env$.html#VERSION-0","e":false,"i":"","n":"VERSION","t":"VERSION: String","d":"com.alecdorrington.server.config.Env","k":"val","x":""},
{"l":"com/alecdorrington/server/html.html#","e":false,"i":"","n":"com.alecdorrington.server.html","t":"com.alecdorrington.server.html","d":"","k":"package","x":""},
{"l":"com/alecdorrington/server/html/Template$.html#","e":false,"i":"","n":"Template","t":"Template","d":"com.alecdorrington.server.html","k":"object","x":""},
{"l":"com/alecdorrington/server/html/Template$.html#apply-fffff73b","e":false,"i":"","n":"apply","t":"apply(viewName: String, pageTitle: String = ..., hotReload: Boolean = ...): String","d":"com.alecdorrington.server.html.Template","k":"def","x":""},
{"l":"com/alecdorrington/server/services.html#","e":false,"i":"","n":"com.alecdorrington.server.services","t":"com.alecdorrington.server.services","d":"","k":"package","x":""},
{"l":"com/alecdorrington/server/services/CoreService$.html#","e":false,"i":"","n":"CoreService","t":"CoreService extends Service","d":"com.alecdorrington.server.services","k":"object","x":""},
{"l":"com/alecdorrington/server/services/CoreService$.html#api-0","e":false,"i":"","n":"api","t":"api: List[Endpoint]","d":"com.alecdorrington.server.services.CoreService","k":"val","x":""},
{"l":"com/alecdorrington/server/services/CoreService$.html#assets-0","e":false,"i":"","n":"assets","t":"assets: Endpoint","d":"com.alecdorrington.server.services.CoreService","k":"val","x":""},
{"l":"com/alecdorrington/server/services/CoreService$.html#health-0","e":false,"i":"","n":"health","t":"health: Endpoint","d":"com.alecdorrington.server.services.CoreService","k":"val","x":""},
{"l":"com/alecdorrington/server/services/CoreService$.html#hotReload-0","e":false,"i":"","n":"hotReload","t":"hotReload: Endpoint","d":"com.alecdorrington.server.services.CoreService","k":"val","x":""},
{"l":"com/alecdorrington/server/services/CoreService$.html#index-0","e":false,"i":"","n":"index","t":"index: Endpoint","d":"com.alecdorrington.server.services.CoreService","k":"val","x":""},
{"l":"com/alecdorrington/server/services/Service.html#","e":false,"i":"","n":"Service","t":"Service(serviceName: String)","d":"com.alecdorrington.server.services","k":"trait","x":""},
{"l":"com/alecdorrington/server/services/Service.html#Capabilities-0","e":false,"i":"","n":"Capabilities","t":"Capabilities = WebSockets & Fs2Streams[IO]","d":"com.alecdorrington.server.services.Service","k":"type","x":""},
{"l":"com/alecdorrington/server/services/Service.html#Endpoint-0","e":false,"i":"","n":"Endpoint","t":"Endpoint = ServerEndpoint[Capabilities, IO]","d":"com.alecdorrington.server.services.Service","k":"type","x":""},
{"l":"com/alecdorrington/server/services/Service.html#all-0","e":false,"i":"","n":"all","t":"all: List[Endpoint]","d":"com.alecdorrington.server.services.Service","k":"val","x":""},
{"l":"com/alecdorrington/server/services/Service.html#api-0","e":false,"i":"","n":"api","t":"api: List[Endpoint]","d":"com.alecdorrington.server.services.Service","k":"def","x":""},
{"l":"com/alecdorrington/server/services/Service.html#docs-0","e":false,"i":"","n":"docs","t":"docs: List[Endpoint]","d":"com.alecdorrington.server.services.Service","k":"val","x":""},
{"l":"com/alecdorrington/server/services/Service.html#metrics-0","e":false,"i":"","n":"metrics","t":"metrics: Endpoint","d":"com.alecdorrington.server.services.Service","k":"val","x":""},
{"l":"com/alecdorrington/server/Main$.html#","e":false,"i":"","n":"Main","t":"Main extends Forever","d":"com.alecdorrington.server","k":"object","x":""},
{"l":"com/alecdorrington/server/Main$.html#run-fffffe81","e":false,"i":"","n":"run","t":"run(args: List[String]): Resource[IO, Unit]","d":"com.alecdorrington.server.Main","k":"def","x":""}];